### PR TITLE
CAP-856: update for ts_salobj 7

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Review by wvreeven — CHANGES_REQUESTED** [review]
The build fails. Please fix and I'll review again.

**Comment by r-owen** [comment]
pr-head is the important test here. pr-merge is expected to fail for all our builds until salobj 7 and ts_xml 11 are released

**Comment by wvreeven** [comment]
My apologies for requesting changes and thanks for pointing out that the conda build is expected to fail.

**Review by wvreeven — APPROVED** [review]
LGTM

**Pull request merged**
